//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryForEmdx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAdmin
    {
        public long AppAdminId { get; set; }
        public string AppAdminEmail { get; set; }
        public string AppAdminPassword { get; set; }
    }
}
