//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingOFDAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRating
    {
        public long RatingId { get; set; }
        public int RatingNumber { get; set; }
        public long RatingCustId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
